#!/bin/sh

echo "🔍 Running ESLint..."
npm run lint

if [ $? -ne 0 ]; then
  echo "❌ Lint errors found. Commit aborted."
  exit 1
fi

echo "✨ Running Prettier..."
npx prettier --check .

if [ $? -ne 0 ]; then
  echo "❌ Code is not formatted. Run 'npm run format'."
  exit 1
fi

echo "✅ Lint and Prettier passed. Proceeding with commit."
